feature/Refactor-handler-into-3-layer-model
phunguyentan109/Staywell pull request #115
Opened 2021-12-09 09:28 UTC by quanhieu

2021-12-09 09:32 UTC, phunguyentan109 commented on handlers/repositories/index.js
> +module.exports.UserRepository = require('./user.repository')
thèn repo vs service thì chắc m export defaul 1 object lớn nha, để sau dùng thì mình chỉ cần services.get hoặc repo.get() kiểu thế

2021-12-09 09:34 UTC, phunguyentan109 requested changes
Mình đưa 3 thư mục mới ra ngoài ngang cấp vs handlers nha, nhưng đừng xóa gì hay sửa gì trong handlers

2021-12-09 09:44 UTC, phunguyentan109 requested changes

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/repositories/user.repository.js
> +  try {
Trong layer repo thì chắc bỏ try catch nha, chỉ để try catch trong service vs controller là dc r

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/services/user.service.js
> +const { genToken } = require('../../utils/token')
cái nào bỏ dấu chân chim dc thì bỏ nha, nhìn cho clean

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/repositories/user.repository.js
> +exports.findOne = async(req, next) => {
trong repositories vs services thì ko truyền req vs res nha, truyền params qua như hàm bt thôi

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/repositories/user.repository.js
> +    }
Hơi nhiều if-else quá ta, đang dự tính gì ak?

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/services/user.service.js
> +    const user = await repositories.UserRepository.create(req, next)
này chữ repositories hơi dài, thôi sau chắc rút gọn lại thành repo cho đỡ tốn máu, mà chắc tên repo thì để repo.User chắc là đủ hiểu r ak

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/services/user.service.js
> +exports.logIn = async(req, res, next) => {
Như đã comment ở trên, chỉ controller ms truyền req, res vs next vào thôi nha

2021-12-09 09:44 UTC, phunguyentan109 commented on handlers/controllers/user.controller.js
> +  return await services.UserService.logIn(req, res, next)
res.status(200).json blah blah => chung quy là return response phải được viết ở đây nha, ở các layer còn lại thì chỉ return value về đây thôi

2021-12-18 12:59 UTC, phunguyentan109 requested changes

2021-12-18 12:59 UTC, phunguyentan109 commented on controllers/bill.controller.js
> +    return res.status(200).json(foundBill).lean().exec()
lean là của mongoose hay gì vậy, sao mà để lean ở đây thế, controller đừng xử lí những cái liên quan đến db nha

2021-12-18 12:59 UTC, phunguyentan109 commented on controllers/price.controller.js
> +    let prices = await services.PriceService.get()
mấy cái tên service hay repo j thì cứ để như tên hàm bình thường thôi m, priceService, kiểu v, có gì apply mấy chỗ còn lại giúp t nha

2021-12-18 12:59 UTC, phunguyentan109 commented on controllers/role.controller.js
> +    return res.json(createdRole)
này m thêm vào cái .status(200) giúp t  vs

2021-12-18 12:59 UTC, phunguyentan109 commented on controllers/user.controller.js
> +    const signUpVal = await services.UserService.signUp(req)
Đừng truyền nguyên cái req qua nha, này truyền thì chỉ truyền cái params hoặc body thôi, tránh mutate cái object req

2021-12-18 12:59 UTC, phunguyentan109 commented on repositories/bill.repository.js
> +  const { params } = req
không truyền nguyên cái req vào nha, request chỉ được dùng ở controller thôi, coi apply mấy chỗ khác giúp t vs

2021-12-18 12:59 UTC, phunguyentan109 commented on repositories/role.repository.js
> +  return await db.Role.create(req)
những cái đơn giản này thì chỉ cần return db.Role.create(req) là được rồi, kết quả đã là promise r, ko cần return qua 1 lần wrap promise nữa
T thấy nhiều chỗ nữa nên coi rà giúp t luôn nha

2021-12-18 12:59 UTC, phunguyentan109 commented on services/contract.service.js
> +  return await repo.ContractRepository.find({
các hàm ở tầng service cũng nên có try catch, thế nên là thêm vô giúp t nha

2021-12-18 13:53 UTC, quanhieu commented on controllers/user.controller.js
> +    const signUpVal = await services.UserService.signUp(req)
cái này truyền qua để lấy req.header.host

2021-12-18 13:55 UTC, quanhieu commented on repositories/bill.repository.js
> +  const { params } = req
cái này là t để tên là req thôi chứ ko phải request http

2021-12-19 02:32 UTC, phunguyentan109 requested changes

2021-12-19 02:32 UTC, phunguyentan109 commented on repositories/contract.repository.js
> +exports.findLean = async(params, populatePath, limitPath) => {
chỗ này chắc bỏ async đi giúp t luôn nha

2021-12-19 02:32 UTC, phunguyentan109 commented on repositories/contract.repository.js
> +exports.findById = async(params) => {
chỗ này cũng bỏ async đi nha, coi dò lại giúp t xem thử còn chỗ nào nữa thì xử luôn

2021-12-19 02:32 UTC, phunguyentan109 commented on utils/dbSupport.js
> +exports.formatQuery = async(val) => {
hàm này ko dùng nữa chắc clear luôn nha

2021-12-19 11:08 UTC, merged